import { buildOverview } from './buildOverview.js';
import { buildIssuesHistory } from './buildIssuesHistory.js';
import { buildStatistics } from './buildStatistics.js';
import { buildStationIndex } from './buildStationIndex.js';
import { buildStationTranslatedNames } from './buildStationTranslatedNames.js';
import { buildStationManifests } from './buildStationManifests.js';
import { buildComponentManifests } from './buildComponentManifests.js';
import { buildComponentIndex } from './buildComponentIndex.js';
import { buildIssueIndex } from './buildIssueIndex.js';
import { buildComponentStatusManifests } from './buildComponentStatusManifests.js';
import { buildFooterManifest } from './buildFooterManifest.js';

buildOverview();
buildIssuesHistory();
buildStatistics();
buildStationIndex();
buildStationTranslatedNames();
buildStationManifests();
buildComponentManifests();
buildComponentIndex();
buildComponentStatusManifests();
buildIssueIndex();
buildFooterManifest();
